### ISSUE TITLE
Doesn't match with the Example from the BMEL

### ISSUE THREAD

**Issue by MalteIwanicki** [lemonhead94/pyNutriScore#1]
The BMEL provides a excel table to calculate the foods score. 
this example: {ENERGY:399,SATURATED_FATS:2.37, SUGAR:26.3, PROTEIN:7.99, SALT:0.82, FIBERS:4.83} should match a score of 9 and a rating of C.
https://www.bmel.de/SharedDocs/Downloads/DE/_Ernaehrung/Lebensmittel-Kennzeichnung/nutri-score-dt-excel-berechnungstabelle.html

**Comment by lemonhead94** [comment]
This is to be expected as it follows the original papers calculation in France. My best guess is that it is calculated differently in Germany. However, if upstream changes or there is a unified way across the EU I‘m inclined to update my implementation. :)

It even states so in the paper: „Across Europe, a number of different front-of-pack labelling schemes co-exist. Nutri-Score, adopted by France in 2017, is one of them.“

**Comment by MalteIwanicki** [comment]
I see.
i just created a version for the german calculation:
https://github.com/MalteIwanicki/NutriScoreCalculator
do you think we can somehow join these two?

**Comment by lemonhead94** [comment]
what we could do is have an initialization country param for the nutri-score class. Then use the different formulas for the calculation and add a reference to it on the readme.
I don’t have the time right now to work on this, but if you want to do a PR. I‘m happy to review / merge.

**Comment by MalteIwanicki** [comment]
Okay. I keep it in mind ^^,  maybe ill find time for it . Anyway happy new year!
